### PR TITLE
Created a third post

### PR DESCRIPTION
**Pull request by SkyExploreWasTaken**
It's on the title

### CODE REVIEW

**Review by ukriu — CHANGES_REQUESTED** [review]
You're changing the other posts! please git pull and add your post again.
You also forgot the comma (`},`) at line 20.

**Comment by SkyExploreWasTaken** [comment]
Uh sorry I think it's a bug with my browser cuz I don't edited your posts. I'm gonna change that

**Comment by ukriu** [comment]
> Uh sorry I think it's a bug with my browser cuz I don't edited your posts. I'm gonna change that

I pushed some changes, you need to sync your repository so there aren't any merge conflits.

**Comment by SkyExploreWasTaken** [comment]
Normally it's okay

**Review by ukriu — APPROVED** [review]

**Pull request merged**
